### ISSUE TITLE
Unhandled rejection Error: ERR invalid DB index

### ISSUE THREAD

**Issue by masciugo** [ember-cli-deploy/ember-cli-deploy-redis#35]
Hi,

with these plugin installed:

    "ember-cli-deploy": "0.5.0-beta.2",
    "ember-cli-deploy-lightning-pack": "0.2.0-beta.5",

whenever the pipeline contacts redis on Heroku I got `ERR invalid DB index `. example on activation:

    |
    +- activate
    |  |
    |  +- redis
    |    - Activating revision `84549e8ecccb5d3ae31c1583f125d2dc`
    Unhandled rejection Error: ERR invalid DB index
        at ReplyParser.<anonymous> (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:317:31)
        at ReplyParser.emit (events.js:107:17)
        at ReplyParser.send_error (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:296:10)
        at ReplyParser.execute (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:181:22)
        at RedisClient.on_data (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:547:27)
        at Socket.<anonymous> (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:102:14)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at Socket.Readable.push (_stream_readable.js:126:10)
        at TCP.onread (net.js:538:20)
    |    - ✔ Activated revision `84549e8ecccb5d3ae31c1583f125d2dc`
    |
    +- didActivate
    |

anything to do with [this issue](https://github.com/LevelbossMike/ember-deploy-redis/issues/13)? It doesn't seem to have any effects on the expected outcome, though.

**Comment by achambers** [comment]
Hi @masciugo Can you please post your redis url that you are sending to? Obviously minus any secret credentials.

**Comment by masciugo** [comment]
redis://h:XXXXXXXXXXXXXXXXXX@ec2-54-235-152-160.compute-1.amazonaws.com:17689

**Comment by achambers** [comment]
Yep, ok. You need to remove the `h`. This is a placeholder for username which isn't needed.

**Comment by masciugo** [comment]
ok solved thanks.. As redis newbie I blindly trusted the URL provided by heroku.
