### ISSUE TITLE
Value already exists for key: app-name:index:default

### ISSUE THREAD

**Issue by varblob** [ember-cli-deploy/ember-cli-deploy-redis#45]
- Value already exists for key: app-name:index:default
    Value already exists for key: app-name:index:default
    undefinedPipeline aborted

It's my first deploy of the app

    "ember-cli-deploy": "0.5.1",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-manifest": "0.1.0",
    "ember-cli-deploy-redis": "0.1.0",
    "ember-cli-deploy-s3": "0.1.0",

**Comment by varblob** [comment]
Cleared redis and tried again and it worked.

**Comment by varblob** [comment]
never mind it didn't actually deployed it just didn't error.  Running again errors 

- `undefined` is not a valid revision key
`undefined` is not a valid revision key
undefinedPipeline aborted


running ember deploy production one more time after that gets

- Value already exists for key: touchcard-app:index:default
Value already exists for key: touchcard-app:index:default
undefinedPipeline aborted

**Comment by lukemelia** [comment]
@varblob you likely need to set the allowOverwrite config option for the redis plugin. See the read me for details.

**Comment by varblob** [comment]
I ended up switching to the lightning pack since things didn't seem to work out of the box.   Works fine now.  Also just want to say this new version is awesome!

**Comment by lukemelia** [comment]
Sounds like we may have some bugs around usage without revisionData in the context. I'm going to reopen to track that.

**Comment by mwpastore** [comment]
I'm just getting ramped up with ember-cli-deploy and can't get past this error, with or without the `allowOverwrite` option. Any suggestions on things to try?

**Comment by mwpastore** [comment]
I installed the lightning pack and disabled the S3 plugin (I'm using PageFront). Now it activates the page but I still get the error at the end. Not sure if this helps or hurts the diagnostic effort...

```
$ ember deploy prod --activate
version: 1.13.13
- Preparing for deploy...

- Uploaded 0 assets
- Success! Released v13 to https://fanriff.pagefrontapp.com
- ✔ Activated revision `1a84b07f7cef50c3df85493c9e782fa1`
[object Object]
undefinedPipeline aborted
```

**Comment by ghedamat** [comment]
@mwpastore can you try to run with --verbose and gist the output?

maybe also your package.json could help in trying to reproduce

thanks!

**Comment by swastik** [comment]
I just ran into this same error. Here's what I see when I run with `--verbose`:

```
version: 1.13.12
Registering hook -> configure[build]
Registering hook -> build[build]
Registering hook -> configure[gzip]
Registering hook -> willUpload[gzip]
Registering hook -> configure[redis]
Registering hook -> upload[redis]
Registering hook -> willActivate[redis]
Registering hook -> activate[redis]
Registering hook -> didDeploy[redis]
Executing pipeline
|
+- configure
|  |
|  +- build
|    - validating config
|    - Missing config: `outputPath`, using default: `tmp/deploy-dist`
|    - config ok
|  |
|  +- gzip
|    - validating config
|    - Missing config: `filePattern`, using default: `**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}`
|    - Missing config: `zopfli`, using default: `false`
|    - Missing config: `keep`, using default: `false`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - config ok
|  |
|  +- redis
|    - validating config
|    - Missing config: `filePattern`, using default: `index.html`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `keyPrefix`, using default: `[Function]`
|    - Missing config: `activationSuffix`, using default: `current`
|    - Missing config: `activeContentSuffix`, using default: `current-content`
|    - Missing config: `revisionKey`, using default: `[Function]`
|    - Missing config: `didDeployMessage`, using default: `[Function]`
|    - Missing config: `redisDeployClient`, using default: `[Function]`
|    - Missing config: `maxRecentUploads`, using default: `10`
|    - config ok
|
+- setup
|
+- willDeploy
|
+- willBuild
|
+- build
|  |
|  +- build
|    - building app to `tmp/deploy-dist` using buildEnv `production`...
|    - ✔  assets/project-6166d5e1f182c736fe3adba5a9d08caf.js
|    - ✔  assets/project-d167fcab4443823c03f204a78b6ff192.css
|    - ✔  assets/vendor-7dbb5eac474c6658404b4313dd6ae6ad.js
|    - ✔  assets/vendor-d2d2d56d71bac7f48cb87981cfac042f.css
|    - ✔  crossdomain.xml
|    - ✔  index.html
|    - ✔  robots.txt
|    - build ok
|
+- didBuild
|
+- willPrepare
|
+- prepare
|
+- didPrepare
|
+- willUpload
|  |
|  +- gzip
|    - gzipping `**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}`
|    - ✔  assets/project-d167fcab4443823c03f204a78b6ff192.css
|    - ✔  robots.txt
|    - ✔  crossdomain.xml
|    - ✔  assets/vendor-d2d2d56d71bac7f48cb87981cfac042f.css
|    - ✔  assets/project-6166d5e1f182c736fe3adba5a9d08caf.js
|    - ✔  assets/vendor-7dbb5eac474c6658404b4313dd6ae6ad.js
|    - gzipped 6 files ok
|
+- upload
|  |
|  +- redis
|    - Uploading `tmp/deploy-dist/index.html`
Unhandled rejection Error: ERR invalid DB index
    at ReplyParser.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:317:31)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_error (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:102:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
|    - Uploaded with key `project:index:default`
|
+- didUpload
|
+- willActivate
|  |
|  +- redis
|
+- activate
|  |
|  +- redis
|    - Activating revision `undefined`
Unhandled rejection Error: ERR invalid DB index
    at ReplyParser.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:317:31)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_error (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:102:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
Unhandled rejection Error: ERR invalid DB index
    at ReplyParser.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:317:31)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_error (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/user/Sites/project/frontend/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:102:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
|    - `undefined` is not a valid revision key
|
+- didFail
`undefined` is not a valid revision key
undefined|
Pipeline aborted
```

**Comment by achambers** [comment]
@swastik Can you please your `deploy.js` here? Also, it looks like you're not running the `revision-data` plugin which I would expect to so. Otherwise, ember-cli-deploy has not idea where to get the unique revision key from for your upload.

**Comment by swastik** [comment]
@achambers — That plugin fixed it! :+1:

**Comment by timini** [comment]
Just had this issue too, could you please stare the requirement for the revision-data plugin in the readme?

**Comment by achambers** [comment]
@timini It is right there in the [Prerequisites](https://github.com/ember-cli-deploy/ember-cli-deploy-redis#prerequisites) section.... `revisionData.revisionKey`

**Comment by timini** [comment]
How about a "quick start" section similar to https://github.com/ember-cli-deploy/ember-cli-deploy-s3#quick-start which mentions you should install ember-cli-deploy-revision-data. 

I think a lot of people will miss the prerequisites section at the bottom of the page, like i did.

**Comment by achambers** [comment]
@timini You mean like this [QuickStart](https://github.com/ember-cli-deploy/ember-cli-deploy-redis#quick-start) section? ;)

You're right, it probably should be in there. This was an oversight.

More than happy to accept a PR from your fine self if you'd like to submit one.

**Comment by ghedamat** [comment]
this should have been addressed
