### ISSUE TITLE
this.readConfig is not a function

### ISSUE THREAD

**Issue by mariogintili** [ember-cli-deploy/ember-cli-deploy-redis#67]
Hello guys and merry christmas 🎅,

Without any version changes or any altered setup in my laptop I noticed `$ ember deploy` now throws an exception:

```
+- didFail
TypeError: this.readConfig is not a function
TypeError: this.readConfig is not a function
    at Object.redisDeployClient (/Users/mariogintili/dev/sunlight/web-client/node_modules/ember-cli-deploy-redis/index.js:55:36)
    at CoreObject.readConfig (/Users/mariogintili/dev/sunlight/web-client/node_modules/ember-cli-deploy-plugin/index.js:63:30)
    at CoreObject.fetchInitialRevisions (/Users/mariogintili/dev/sunlight/web-client/node_modules/ember-cli-deploy-redis/index.js:137:38)
    at Object.fn (/Users/mariogintili/dev/sunlight/web-client/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/mariogintili/dev/sunlight/web-client/node_modules/ember-cli-deploy/lib/models/pipeline.js:175:19)
    at tryCatch (/Users/mariogintili/dev/sunlight/web-client/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/mariogintili/dev/sunlight/web-client/node_modules/rsvp/dist/rsvp.js:553:13)
    at /Users/mariogintili/dev/sunlight/web-client/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/Users/mariogintili/dev/sunlight/web-client/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
|
Pipeline aborted
```

My package.json is as follows

```
    "ember-cli-deploy": "1.0.0-beta.1",
    "ember-cli-deploy-revision-data": "0.3.2",
    "ember-cli-deploy-display-revisions": "0.2.2",
    "ember-cli-deploy-lightning-pack": "0.6.7",
    "ember-cli-deploy-ssh-tunnel": "0.2.2",
```

I tried upgrading the `ember-cli-deploy-lighting-pack` to [the latest release to date - 0.6.10](https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/blob/master/package.json#L3)

which now yields the following:

```
+- prepare
|  |
|  +- revision-data
- creating revision data using `file-hash`
- generated revision data for revision: `997780b824c374fc5ce269e95918b032`
|
+- didPrepare
|
+- fetchInitialRevisions
|  |
|  +- redis
- Listing initial revisions for key: `sunlight-web-client`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/Users/mariogintili/dev/sunlight/web-client/node_modules/ssh2/lib/client.js:569:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I can confirm no SSH keys in my setup have changed(both on my end and on our servers) and that I have a more than stable internet connection - any help is greatly appreciated. Some additional info:

```
ember --version
ember-cli: 2.7.0
node: 6.9.1
os: darwin x64
```

**Comment by noslouch** [comment]
Also experiencing this today

**Comment by lukemelia** [comment]
@mariogintili @noslouch if you pop into to the #ec-deploy channel on the ember community slack, I'd be happy to help debug. The upgrade you already did is unfortunately necessary due a semver violation. The new error, however, I'm not sure what is causing.

**Comment by mariogintili** [comment]
@lukemelia my apologies ! 

just checked the list of events on my aws beanstalk environment and some VPC settings where changed causing this error - thanks for coming back to me anyways 😄
