### ISSUE TITLE
Error in 1.0.1: this._listRevisions(...).then is not a function

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy-redis#77]
```
TypeError: this._listRevisions(...).then is not a function
TypeError: this._listRevisions(...).then is not a function
    at CoreObject.fetchRevisions (/Users/lmelia/p/yapp/dashboard/node_modules/ember-cli-deploy-redis/lib/redis.js:75:43)
    at CoreObject.fetchInitialRevisions (/Users/lmelia/p/yapp/dashboard/node_modules/ember-cli-deploy-redis/index.js:149:47)
```

**Comment by lukemelia** [comment]
Addressed by #78
